name: Android APK (Cordova, Gradle 8.7)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node (Cordova CLI)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses + install SDKs
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install Cordova
        run: npm i -g cordova@12

      - name: Prepare Android platform
        run: |
          cordova platform rm android || true
          cordova platform add android@12.0.1

      - name: Ensure Gradle wrapper 8.7 (platform)
        run: |
          cd platforms/android
          chmod +x gradlew || true
          ./gradlew wrapper --gradle-version 8.7
          chmod +x gradlew

      - name: Build Debug APK
        run: |
          cd platforms/android
          ./gradlew assembleDebug --stacktrace --warning-mode all

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Spades-debug-apk
          path: platforms/android/app/build/outputs/apk/debug/*.apk
