name: Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Cordova
        run: npm i -g cordova
      - name: Android SDK
        uses: android-actions/setup-android@v3
      - name: SDK packages
        run: sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest"
      - name: Build debug APK (cordova-android@12)
        run: |
          cordova platform add android@12.0.1
          cordova build android --debug --no-telemetry
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SpadesTouch-debug
          path: platforms/android/app/build/outputs/apk/debug/*.apk
