name: Android APK (Cordova, Gradle 8.7)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node (Cordova CLI)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses + install SDKs
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install Cordova
        run: npm i -g cordova@12

      - name: Prepare Android platform
        run: |
          cordova platform rm android || true
          cordova platform add android@12.0.1
          ls -la
          ls -la platforms || true
          ls -la platforms/android || true

      # Install Gradle 8.7 on the runner (so wrapper generation uses 8.7, not 9.x)
      - name: Install Gradle 8.7 (SDKMAN)
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          echo "$HOME/.sdkman/candidates/gradle/current/bin" >> $GITHUB_PATH
          gradle -v

      # Generate wrapper files INSIDE platforms/android using Gradle 8.7
      - name: Generate Gradle wrapper 8.7 in platform
        run: |
          gradle -p platforms/android wrapper --gradle-version 8.7
          ls -la platforms/android
          chmod +x platforms/android/gradlew

      # Now build with the platform wrapper (safe)
      - name: Build Debug APK
        run: |
          cd platforms/android
          ./gradlew assembleDebug --stacktrace --warning-mode all

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Spades-debug-apk
          path: platforms/android/app/build/outputs/apk/debug/*.apk
